name: Publish
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: write
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
          - os: macos-14
            platform: darwin
            arch: x64
          - os: macos-14
            platform: darwin
            arch: arm64
          - os: windows-2022
            platform: win32
            arch: x64
          - os: windows-2022
            platform: win32
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build / ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
        with:
          force-install: true
      - run: choco upgrade llvm
        if: ${{ matrix.platform == 'win32' }}
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          prefix: prebuilds/${{ matrix.platform }}-${{ matrix.arch }}
      - uses: holepunchto/actions/upload-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          prefix: prebuilds
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    needs: prebuild
    name: Publish
    steps:
      - uses: holepunchto/actions/node-base@v1
        with:
          force-install: true
      - uses: holepunchto/actions/download-prebuilds@v1
        with:
          prefix: npm
      - uses: holepunchto/actions/publish@v1
        with:
          workspaces: true
          include-workspace-root: true
